
void FillRand( float *mas, int size );
void FillIncr( float *mas, int size );
void FillDecr( float *mas, int size );
void FillMostly( float *mas, int size );
void FillEq( float *mas, int size );
void OutMas( float *mas, int size );
int CheckSort( float *mas, int size );
void Swap( float *A, float *B );
void BubbleSort( float *mas, int size );
void BubbleSortAdv( float *mas, int size );
void InsertionSort( float *mas, int size );
void SelectionSort( float *mas, int size );
void MergeSort( float *mas, int size );
void QuickSort( float *mas, int size );
void HeapSort( float *mas, int size );
