
void Fill0( int *mas, int size );
void FillRand( int *mas, int size, int n );
void FillIncr( int *mas, int size );
void FillDecr( int *mas, int size );
void OutMas( int *mas, int size );
void GetMinMax( int *mas, int size, int *mi, int *ma );
double GetAverage( int *mas, int size );
void FillWithStep( int *mas, int size, int a, int b );
void Reverse( int *mas, int size );
void GetMaxDigitSum( int *mas, int size );
void PrintOutPrime( int *mas, int size );
int CountSimmetrical( int *mas, int size );
